// AspNetCore/React/AdvancedSearch/ClientApp/src/components/NavMenu.js
import React, { Component } from 'react';
import { Collapse, Container, Navbar, NavbarBrand, NavbarToggler, NavItem, NavLink } from 'reactstrap';
import { Link } from 'react-router-dom';
import './NavMenu.css';

export class NavMenu extends Component {
  static displayName = NavMenu.name;

  constructor (props) {
    super(props);

    this.toggleNavbar = this.toggleNavbar.bind(this);
    this.state = {
      collapsed: true
    };
  }

  toggleNavbar () {
    this.setState({
      collapsed: !this.state.collapsed
    });
  }

  render () {
    return (
      <header>
        <Navbar className="navbar-expand-sm navbar-toggleable-sm ng-white border-bottom box-shadow mb-3" light>
          <Container>
                    <NavbarBrand tag={Link} to="/">EasyQuery React Demo (Advanced Search scenario) </NavbarBrand>
            <NavbarToggler onClick={this.toggleNavbar} className="mr-2" />
            <Collapse className="d-sm-inline-flex flex-sm-row-reverse" isOpen={!this.state.collapsed} navbar>
              <ul className="navbar-nav flex-grow">
                <NavItem>
                  <NavLink tag={Link} className="text-dark" to="/">Home</NavLink>
                </NavItem>
                <NavItem>
                  <NavLink tag={Link} className="text-dark" to="/counter">Counter</NavLink>
                </NavItem>
                <NavItem>
                  <NavLink tag={Link} className="text-dark" to="/fetch-data">Fetch data</NavLink>
                </NavItem>
                <NavItem>
                  <NavLink tag={Link} className="text-dark" to="/easy-query">EasyQuery</NavLink>
                </NavItem>
              </ul>
            </Collapse>
          </Container>
        </Navbar>
      </header>
    );
  }
}

// AspNetCore/Stencil/AdvancedSearch/ClientApp/src/components/nav-menu/nav-menu.tsx
import { Component, State, h } from '@stencil/core';

@Component({
    tag: 'nav-menu',
    styleUrl: 'nav-menu.css'
})
export class NavMenu {

    @State() isExpanded = false;

    toggle = () => {
        this.isExpanded = !this.isExpanded;
    }

    render() {

        let collapseClass = "navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse";
        if (this.isExpanded) {
            collapseClass += " show";
        }

        return (
            <header>
                <nav class='navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3'>
                    <div class="container">
                        <stencil-route-link anchorClass="navbar-brand" url="/">
                            EqStencilDemo
                        </stencil-route-link>
                        <button class="navbar-toggler" type="button" aria-expanded={this.isExpanded} data-toggle="collapse" data-target=".navbar-collapse" aria-label="Toggle navigation" onClick={this.toggle}>
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class={collapseClass}>
                            <ul class="navbar-nav flex-grow">
                                <li class="nav-item">
                                    <stencil-route-link anchorClass="nav-link text-dark" activeClass="link-active" url="/">
                                        Home
                                    </stencil-route-link>
                                </li>
                                <li class="nav-item">
                                    <stencil-route-link anchorClass="nav-link text-dark" activeClass="link-active" url="/counter">
                                        Counter
                                    </stencil-route-link>
                                </li>
                                <li class="nav-item">
                                    <stencil-route-link anchorClass="nav-link text-dark" activeClass="link-active" url="/fetch-data">
                                        Fetch Data
                                    </stencil-route-link>
                                </li>
                                <li class="nav-item">
                                    <stencil-route-link anchorClass="nav-link text-dark" activeClass="link-active" url="/easy-query">
                                        EasyQuery
                                    </stencil-route-link>
                                </li>
                                <li class="nav-item">
                                    <stencil-route-link anchorClass="nav-link text-dark" activeClass="link-active" url="/filter-bar">
                                        Data Filter
                                    </stencil-route-link>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
        )
    }
}
